/*
 * This file was generated by the Gradle 'init' task.
 *
^ * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.21")
    groovy
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

tasks.test {
    useJUnitPlatform()
}

val groovyAllVersion = "2.5.5"
val kotlinTestVersion = "3.3.2"
val spockVersion = "1.3-groovy-2.5"
val junitVersion = "5.4.2"
val assertjVersion = "3.12.2"

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.codehaus.groovy:groovy-all:$groovyAllVersion")

    // Use the KotlinTest library.
    testImplementation("io.kotlintest:kotlintest-runner-junit5:$kotlinTestVersion")
    testImplementation("org.spockframework:spock-core:$spockVersion")
    testImplementation("org.junit.jupiter:junit-jupiter:$junitVersion")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:$junitVersion")
    testImplementation("org.assertj:assertj-core:$assertjVersion")
}
