/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jvm.testing.frameworks

class GeometricShapeHelper {

    fun calculateArea(shape: Shape): Int {
        return when(shape){
            is Square -> shape.side * shape.side
            is Rectangle -> shape.base * shape.height
            else -> 0
        }
    }
}


interface Shape
data class Square(val side: Int) : Shape
data class Rectangle(val base: Int, val height: Int) : Shape